// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGfE5kyGQQicc9rXuGg6dNHLjTaP-zUHo',
    appId: '1:162564117259:web:10867addfa55fcb994080e',
    messagingSenderId: '162564117259',
    projectId: 'tareeq-app-b532e',
    authDomain: 'tareeq-app-b532e.firebaseapp.com',
    storageBucket: 'tareeq-app-b532e.appspot.com',
    measurementId: 'G-YD7FYHF8GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuDq0O3yLobzhgm4KUonIBFS50aQpT6rY',
    appId: '1:162564117259:android:165ed74b61a5c8ed94080e',
    messagingSenderId: '162564117259',
    projectId: 'tareeq-app-b532e',
    storageBucket: 'tareeq-app-b532e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi60PUxV00_0qTMaznfnZiw02F1Vx0ESw',
    appId: '1:162564117259:ios:b2e60abcc9a843b494080e',
    messagingSenderId: '162564117259',
    projectId: 'tareeq-app-b532e',
    storageBucket: 'tareeq-app-b532e.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi60PUxV00_0qTMaznfnZiw02F1Vx0ESw',
    appId: '1:162564117259:ios:b2e60abcc9a843b494080e',
    messagingSenderId: '162564117259',
    projectId: 'tareeq-app-b532e',
    storageBucket: 'tareeq-app-b532e.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGfE5kyGQQicc9rXuGg6dNHLjTaP-zUHo',
    appId: '1:162564117259:web:832b354151160d1994080e',
    messagingSenderId: '162564117259',
    projectId: 'tareeq-app-b532e',
    authDomain: 'tareeq-app-b532e.firebaseapp.com',
    storageBucket: 'tareeq-app-b532e.appspot.com',
    measurementId: 'G-9C1DXTL453',
  );
}
